version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    env_file: .env.example
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    env_file: .env.example
    ports:
      - "3000:3000"
    depends_on:
      - backend
